/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

export const AVAILABLE_PLUGIN_TYPES = [
  {
    value: 'mysql-aurora-database-plugin',
    displayName: 'MySQL (Aurora)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'mysql-legacy-database-plugin',
    displayName: 'MySQL (Legacy)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'mysql-database-plugin',
    displayName: 'MySQL/MariaDB',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'mysql-rds-database-plugin',
    displayName: 'MySQL (RDS)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'postgresql-database-plugin',
    displayName: 'PostgreSQL',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'druid-database-plugin',
    displayName: 'Apache Druid',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'authenticator', group: 'pluginConfig' },
      { attr: 'authorizer', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'elasticsearch-database-plugin',
    displayName: 'Elasticsearch',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'ca_path', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'use_old_xpack', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'etcd-database-plugin',
    displayName: 'etcd',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'endpoints', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'dial_timeout', group: 'pluginConfig' },
      { attr: 'use_tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'hana-database-plugin',
    displayName: 'SAP HANA',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'ignite-database-plugin',
    displayName: 'Apache Ignite',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'cache_name', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'kafka-database-plugin',
    displayName: 'Apache Kafka',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'brokers', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'mechanism', group: 'pluginConfig' },
      { attr: 'use_tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'milvus-database-plugin',
    displayName: 'Milvus',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'token', group: 'pluginConfig', show: false },
      { attr: 'db_name', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'mongodb-database-plugin',
    displayName: 'MongoDB',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'write_concern', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'socket_timeout', group: 'pluginConfig' },
      { attr: 'connect_timeout', group: 'pluginConfig' },
      { attr: 'server_selection_timeout', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'mssql-database-plugin',
    displayName: 'Microsoft SQL Server',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'contained_db', group: 'pluginConfig' },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'neo4j-database-plugin',
    displayName: 'Neo4j',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'uri', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'database', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'oracle-database-plugin',
    displayName: 'Oracle',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'qdrant-database-plugin',
    displayName: 'Qdrant (static-only)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'api_key', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'ca_path', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
    ],
  },
  {
    value: 'rabbitmq-database-plugin',
    displayName: 'RabbitMQ',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'connection_uri', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'solr-database-plugin',
    displayName: 'Apache Solr',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'weaviate-database-plugin',
    displayName: 'Weaviate (static-only)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'api_key', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'ca_path', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
    ],
  },
  {
    value: 'remote-druid-plugin',
    displayName: 'Apache Druid (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'authenticator', group: 'pluginConfig' },
      { attr: 'authorizer', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-elasticsearch-plugin',
    displayName: 'Elasticsearch (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'use_old_xpack', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-etcd-plugin',
    displayName: 'etcd (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'endpoints', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'dial_timeout', group: 'pluginConfig' },
      { attr: 'use_tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-hana-plugin',
    displayName: 'SAP HANA (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-ignite-plugin',
    displayName: 'Apache Ignite (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'cache_name', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-kafka-plugin',
    displayName: 'Apache Kafka (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'brokers', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'mechanism', group: 'pluginConfig' },
      { attr: 'use_tls', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-milvus-plugin',
    displayName: 'Milvus (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'token', group: 'pluginConfig', show: false },
      { attr: 'db_name', group: 'pluginConfig' },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-mongodb-plugin',
    displayName: 'MongoDB (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'write_concern', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-mssql-plugin',
    displayName: 'Microsoft SQL Server (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'contained_db', group: 'pluginConfig' },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-neo4j-plugin',
    displayName: 'Neo4j (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'uri', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'database', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-oracle-plugin',
    displayName: 'Oracle (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'connection_url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'max_open_connections', group: 'pluginConfig' },
      { attr: 'max_idle_connections', group: 'pluginConfig' },
      { attr: 'max_connection_lifetime', group: 'pluginConfig' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-qdrant-plugin',
    displayName: 'Qdrant (Remote, static-only)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'api_key', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'ca_path', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
    ],
  },
  {
    value: 'remote-rabbitmq-plugin',
    displayName: 'RabbitMQ (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'connection_uri', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'tls_ca', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_certificate', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'tls_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-solr-plugin',
    displayName: 'Apache Solr (Remote)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'password_policy' },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'username', group: 'pluginConfig', show: false },
      { attr: 'password', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'username_template', group: 'pluginConfig' },
      { attr: 'root_rotation_statements', group: 'statements' },
    ],
  },
  {
    value: 'remote-weaviate-plugin',
    displayName: 'Weaviate (Remote, static-only)',
    fields: [
      { attr: 'plugin_name' },
      { attr: 'name' },
      { attr: 'verify_connection', show: false },
      { attr: 'spoke_name', group: 'pluginConfig' },
      { attr: 'url', group: 'pluginConfig' },
      { attr: 'api_key', group: 'pluginConfig', show: false },
      { attr: 'ca_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'ca_path', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_cert', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'client_key', group: 'pluginConfig', subgroup: 'TLS options' },
      { attr: 'insecure', group: 'pluginConfig', subgroup: 'TLS options' },
    ],
  },
];

export const ROLE_FIELDS = {
  static: ['username', 'rotation_period'],
  dynamic: ['default_ttl', 'max_ttl'],
};

export const STATEMENT_FIELDS = {
  static: {
    default: ['rotation_statements'],
    'mysql-database-plugin': [],
    'mysql-aurora-database-plugin': [],
    'mysql-legacy-database-plugin': [],
    'mysql-rds-database-plugin': [],
    'postgresql-database-plugin': [],
    'druid-database-plugin': [],
    'remote-druid-plugin': [],
    'elasticsearch-database-plugin': [],
    'remote-elasticsearch-plugin': [],
    'etcd-database-plugin': [],
    'remote-etcd-plugin': [],
    'hana-database-plugin': ['rotation_statements'],
    'remote-hana-plugin': ['rotation_statements'],
    'ignite-database-plugin': [],
    'remote-ignite-plugin': [],
    'kafka-database-plugin': [],
    'remote-kafka-plugin': [],
    'milvus-database-plugin': [],
    'remote-milvus-plugin': [],
    'mongodb-database-plugin': [],
    'remote-mongodb-plugin': [],
    'mssql-database-plugin': [],
    'remote-mssql-plugin': [],
    'oracle-database-plugin': [],
    'remote-oracle-plugin': [],
    'qdrant-database-plugin': [],
    'remote-qdrant-plugin': [],
    'rabbitmq-database-plugin': [],
    'remote-rabbitmq-plugin': [],
    'neo4j-database-plugin': [],
    'remote-neo4j-plugin': [],
    'solr-database-plugin': [],
    'remote-solr-plugin': [],
    'weaviate-database-plugin': [],
    'remote-weaviate-plugin': [],
  },
  dynamic: {
    default: ['creation_statements', 'revocation_statements', 'rollback_statements', 'renew_statements'],
    'mysql-database-plugin': ['creation_statements', 'revocation_statements'],
    'mysql-aurora-database-plugin': ['creation_statements', 'revocation_statements'],
    'mysql-legacy-database-plugin': ['creation_statements', 'revocation_statements'],
    'mysql-rds-database-plugin': ['creation_statements', 'revocation_statements'],
    'postgresql-database-plugin': [
      'creation_statements',
      'revocation_statements',
      'rollback_statements',
      'renew_statements',
    ],
    'druid-database-plugin': ['creation_statements'],
    'remote-druid-plugin': ['creation_statements'],
    'elasticsearch-database-plugin': ['creation_statements'],
    'remote-elasticsearch-plugin': ['creation_statements'],
    'etcd-database-plugin': ['creation_statements'],
    'remote-etcd-plugin': ['creation_statements'],
    'hana-database-plugin': ['creation_statements', 'revocation_statements'],
    'remote-hana-plugin': ['creation_statements', 'revocation_statements'],
    'ignite-database-plugin': ['creation_statements', 'revocation_statements'],
    'remote-ignite-plugin': ['creation_statements', 'revocation_statements'],
    'kafka-database-plugin': ['creation_statements'],
    'remote-kafka-plugin': ['creation_statements'],
    'milvus-database-plugin': ['creation_statements'],
    'remote-milvus-plugin': ['creation_statements'],
    'mongodb-database-plugin': ['creation_statements', 'revocation_statements'],
    'remote-mongodb-plugin': ['creation_statements', 'revocation_statements'],
    'mssql-database-plugin': ['creation_statements', 'revocation_statements'],
    'remote-mssql-plugin': ['creation_statements', 'revocation_statements'],
    'oracle-database-plugin': ['creation_statements', 'revocation_statements'],
    'remote-oracle-plugin': ['creation_statements', 'revocation_statements'],
    'qdrant-database-plugin': [],
    'remote-qdrant-plugin': [],
    'rabbitmq-database-plugin': ['creation_statements'],
    'remote-rabbitmq-plugin': ['creation_statements'],
    'neo4j-database-plugin': ['creation_statements'],
    'remote-neo4j-plugin': ['creation_statements'],
    'solr-database-plugin': ['creation_statements'],
    'remote-solr-plugin': ['creation_statements'],
    'weaviate-database-plugin': [],
    'remote-weaviate-plugin': [],
  },
};

export function getStatementFields(type, plugin) {
  if (!type) return null;
  let dbValidFields = STATEMENT_FIELDS[type].default;
  if (STATEMENT_FIELDS[type][plugin]) {
    dbValidFields = STATEMENT_FIELDS[type][plugin];
  }
  return dbValidFields;
}

export function getRoleFields(type) {
  if (!type) return null;
  return ROLE_FIELDS[type];
}
